package pe.edu.unsch.entities;
// Generated 05-jul-2019 1:43:54 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cargaacademica generated by hbm2java
 */
@Entity
@Table(name = "cargaacademica", catalog = "cargadb")
public class Cargaacademica implements java.io.Serializable {

	private Integer idCargaAcademica;
	private Docente docente;
	private Semestreacademico semestreacademico;
	private int numHorasSemanales;

	public Cargaacademica() {
	}

	public Cargaacademica(Docente docente, Semestreacademico semestreacademico, int numHorasSemanales) {
		this.docente = docente;
		this.semestreacademico = semestreacademico;
		this.numHorasSemanales = numHorasSemanales;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCargaAcademica", unique = true, nullable = false)
	public Integer getIdCargaAcademica() {
		return this.idCargaAcademica;
	}

	public void setIdCargaAcademica(Integer idCargaAcademica) {
		this.idCargaAcademica = idCargaAcademica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDocente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSemestreAcademico", nullable = false)
	public Semestreacademico getSemestreacademico() {
		return this.semestreacademico;
	}

	public void setSemestreacademico(Semestreacademico semestreacademico) {
		this.semestreacademico = semestreacademico;
	}

	@Column(name = "NumHorasSemanales", nullable = false)
	public int getNumHorasSemanales() {
		return this.numHorasSemanales;
	}

	public void setNumHorasSemanales(int numHorasSemanales) {
		this.numHorasSemanales = numHorasSemanales;
	}

}
