package pe.edu.unsch.entities;
// Generated 05-jul-2019 1:43:54 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "cargadb")
public class Docente implements java.io.Serializable {

	private int idDocente;
	private Usuario usuario;
	private String nombre;
	private Set<Cargaacademica> cargaacademicas = new HashSet<Cargaacademica>(0);

	public Docente() {
	}

	public Docente(int idDocente, Usuario usuario, String nombre) {
		this.idDocente = idDocente;
		this.usuario = usuario;
		this.nombre = nombre;
	}

	public Docente(int idDocente, Usuario usuario, String nombre, Set<Cargaacademica> cargaacademicas) {
		this.idDocente = idDocente;
		this.usuario = usuario;
		this.nombre = nombre;
		this.cargaacademicas = cargaacademicas;
	}

	@Id

	@Column(name = "idDocente", unique = true, nullable = false)
	public int getIdDocente() {
		return this.idDocente;
	}

	public void setIdDocente(int idDocente) {
		this.idDocente = idDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<Cargaacademica> getCargaacademicas() {
		return this.cargaacademicas;
	}

	public void setCargaacademicas(Set<Cargaacademica> cargaacademicas) {
		this.cargaacademicas = cargaacademicas;
	}

}
