package pe.edu.unsch.entities;
// Generated 05-jul-2019 1:43:54 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "cargadb")
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private String usuario;
	private String password;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public Usuario() {
	}

	public Usuario(int idUsuario, String usuario, String password) {
		this.idUsuario = idUsuario;
		this.usuario = usuario;
		this.password = password;
	}

	public Usuario(int idUsuario, String usuario, String password, Set<Docente> docentes) {
		this.idUsuario = idUsuario;
		this.usuario = usuario;
		this.password = password;
		this.docentes = docentes;
	}

	@Id

	@Column(name = "idUsuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "Usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
